name: Zaapi
token: token
secret: "1234"
server:
  host: 0.0.0.0
  port: 8080
  enable: true
  debug: false
  maneger: false
  swagger: false
database:
  host: localhost
  port: 5432
  user: zaapi
  password: zaapi
  name: zaapi
redis:
  host: localhost
  port: 6379
  password: ""
  db: 0
webhook:
  global: http://localhost:8080
  local: http://localhost:8080
  enabled: false
  timeout: 5
  retries: 3
whatsapp:
  version: latest
media:
  path: assets
